### PR TITLE
Make Amiga naming consistent and grouped with Commodore

### PR DESCRIPTION
**Pull request by limi**
Hi! I am one of the maintainers of the https://amiga.vision project (formerly known as MegaAGS), the “de facto” Amiga setup for MiSTer with deep integration with MiSTer’s scaler, shared drives, etc — open source, and built by members of the original Amiga demo scene in the 90s. You can find it here on GitHub: https://github.com/amigavision/AmigaVision

We recently made a major update to the setup, making full use of of MGL files to offer dedicated setups for Amiga 500, Amiga 500HD, Amiga 600HD, as well as moving the main setup to an independent setup called simply “Amiga”. It looks like this when you boot up the MiSTer:

Then we started getting reports of people now having two entries called “Amiga” in their menu, and — as you can probably guess — this is because they are using `update_all` and downloading the default setup for names.txt hosted in this repository.

We explicitly chose to name our MGL files just “Amiga *” since we have more than one model, and what we had experienced before was that people used names.txt to rename the Commodore computers “Commodore 64”, “Commodore Amiga”, etc — which makes sense as a grouping of the default cores.

I understand that the `CHAR18` category attempts to list the computers without their manufacturers. However, it still names the 8-bit computers from Commodore with the manufacturer name — “Commodore 16”, “Commodore 64” etc — so this appears a bit inconsistent. As “Commodore Amiga” fits just fine in the 18 characters, I propose that we rename it for consistency, and — for obvious self-serving reasons — lets AmigaVision have all the various model setups using the MGL files without namespace collisions, keeping the de-facto Amiga setup as clean as possible while reducing confusion.

(Also, one of the names was “Comm. Amiga”, which I don’t understand how makes sense in either format, so I expanded that one to "Commodore Amiga” too)

I am happy to discuss other potential solutions to this, but wanted to attach a Pull Request for convenience if you are OK with this change.

Thanks!

### CODE REVIEW

**Comment by ThreepwoodLeBrush** [comment]
Hi Alex, your proposal is sound and I will look into it properly when I can
work on names.txt again. Please give me about two weeks of time.

I wanted to leave you this quick reply so you know that I am not ignoring
your PR.

**Comment by limi** [comment]
Thank you! No rush, take your time.

**Review by ThreepwoodLeBrush — APPROVED** [review]
Thank you for fixing this oversight!

**Comment by ThreepwoodLeBrush** [comment]
Regarding the naming of the Amiga Vision setups, maybe it is worth considering to prepend the MGL names with e.g. "AV" for "Amiga Vision" ("AV Amiga", "AV Amiga 500HD" etc.) to indicate that these are special setups and not just raw core entries. You would still have the entries grouped in the A-Range, where people would expect to find them.

**Comment by ThreepwoodLeBrush** [comment]
Just having worked on the files again, I am wondering if it would make more sense to remove the manufacturer in the common entries of the names-files.

The common files are not per se meant to have no manufacturer, but list the systems in a way that feels like the common way the systems were refered to, but that is not objective. That may need changing to strict no-manufacturer to be actually useful, but then we had a names collision with Amiga Vision.

To my knowledge nobody complained yet about the current naming scheme and I am rather neutral about refactoring wether this part needs work, but it would be a point in favor of prepending the Amiga Vision entries with AV. If you folks don't want to do that, no harm done either way.

**Comment by ThreepwoodLeBrush** [comment]
As a headsup, I am in the process of improving consistency in names.txt, which will result in Commodore computer cores loosing "Commodore" in the Common variants of names.txt (Commodore 16 > C16). As such Minimig will be "Amiga".

I will add dedicated entries for AmigaVision MGLs. The entries will look like:

```
MGL           Char18              Char28
Amiga         AV Amiga (MegaAGS)  AmigaVision Amiga (MegaAGS)
Amiga 500     AV Amiga 500        AmigaVision Amiga 500
Amiga 500HD   AV Amiga 500HD      AmigaVision Amiga 500HD
Amiga 600HD   AV Amiga 600HD      AmigaVision Amiga 600HD
```

This will keep all your MGLs as a nice block in the A-range and distinguishes them from the bare minimig core.

Please inform me when you would prefer "(MegaAGS)" to be left out.

**Comment by limi** [comment]
Yes, MegaAGS is not needed. 

This change does needlessly complicate our documentation though, since we cannot reliably know what the entry is on a given MiSTer since we can’t know if they use `update_all` or not — which was the point of using the MGLs in the first place — have a way to make it be consistent. 

As far as I know, nobody back in the day referred to the Commodore 16 or 64 as “C16” or “C64”, so this seems like a step in the wrong direction.

**Pull request merged**
